### ISSUE TITLE
block location of the picture

### ISSUE THREAD

**Issue by MrWhiteHomeman** [Edward-Lin/inpainting#1]
Thank you for sharing your  code ！！！I appreciate it ！！！
Recently,  I have studied your code,    I have a  problem   ,  in the ' inpaint.py ' when I  choose the 'center' from the '(center, random)',  I want to block the center of the picture.
But in the sample folder ,  I find the  picture,  block location is  random ,  I don' t  know why

**Comment by Agent-INF** [comment]
My code was designed to train with only random block, and validate/test with random or center block, because of some personal reasons. I update the code, now it could train/validate/test with both random and center block.

**Comment by MrWhiteHomeman** [comment]
Thank u！！！I have solved it,   your code is great,   appreciate it ！！！
